name: Download Artifact

on:
  repository_dispatch:
    types: [download_artifact]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug before download
        run: |
          echo "Attempting to download artifact 'playwright-results'"
          ls -la test-results || echo "test-results directory not found"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-results
          path: playwright-results.txt

      - name: Move results to directory
        run: |
          mkdir -p test-results
          mv playwright-results.txt test-results/

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git checkout results
          git pull origin results
          
          git add test-results/playwright-results.txt
          git commit -m "Add Playwright test results"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/yumis56/is373-devops.git results
