name: Playwright Tests
on:
  repository_dispatch:
    types: [hexo-site-updated]
  workflow_run:
    workflows: ["Deploy Test Hexo"]
    types: [completed]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root
  

      - name: Upload Playwright Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            results
            playwright-report
            test-results.json
          retention-days: 7

      - name: Upload Playwright Screenshots and Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            screenshots
            videos
            traces
          retention-days: 7

      #- name: Publish Test Summary Results
      #  run: npx github-actions-ctrf ctrf/ctrf-report.json
