name: Test Hexo Site

on:
  repository_dispatch:
    types: [hexo-site-updated]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Hexo site Docker image
      run: docker pull ghcr.io/yumis56/is373-project/hexo-site:${{ github.event.client_payload.sha }}

    - name: Run tests
      run: |
        docker run --name hexo-site -d -p 8080:80 ghcr.io/yumis56/is373-project/hexo-site:${{ github.event.client_payload.sha }}
        docker run --network host mcr.microsoft.com/playwright:v1.39.0-focal npx playwright test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
